---
- name: set vars
  set_fact:
    docker_image: '{{ role_jellyseerr_image }}'
    docker_container: '{{ role_jellyseerr_container }}'
    docker_tz: '{{ role_jellyseerr_tz }}'
    docker_volume: '{{ role_jellyseerr_volume }}_config'
    docker_network: '{{ role_jellyseerr_network }}'

- name: Ensure image is pulled
  community.docker.docker_image:
    name: "{{ docker_image }}"
    source: pull
    force_source: yes
  register: pulled

- name: Remove container
  community.docker.docker_container:
    name: "{{ docker_container }}"
    state: absent
  when: pulled.changed

- name: Get infos on container
  community.docker.docker_container_info:
    name: "{{ docker_container }}"
  register: result

- name: Create volume
  community.docker.docker_volume:
    name: "{{ docker_volume }}"

- name: Create network
  community.docker.docker_network:
    name: "{{ docker_network }}"
    driver_options:
          com.docker.network.bridge.name: "br-{{ docker_network }}"

- name: Create jellyseerr container
  community.docker.docker_container:
    image: "{{ docker_image }}"
    volumes:
     - '{{ docker_volume }}:/app/config:Z'
    env:
      TZ: '{{ docker_tz }}'
      LOG_LEVEL: 'debug'
    name: "{{ docker_container }}"
    networks:
     - name: "{{ docker_network }}"
    restart_policy: unless-stopped
    state: started
  when: 
    pulled.changed
    or
    result.exists == false
